config/routes.rb
RoRZad7::Application.routes.draw do
  devise_for :users

  resources :groups do
    member do
      post :invite
    end
    post :accept
  end

  root :to => "home#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates_presence_of :name, :desc
  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships
  has_many :invitations, :dependent => :destroy

  def member?(user)
    users.include?(user)
  end
  def invited?(user)
    invitations.map { |t| t.user_id }.include?(user.id)
  end
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  validates_uniqueness_of :user_id, :scope => :group_id
  belongs_to :group
  belongs_to :user
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  validates_uniqueness_of :user_id, :scope => :group_id
  belongs_to :group
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :memberships
  has_many :groups, :through => :memberships
  has_many :invitations
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end
  def create
    @group = Group.create(params[:group])
    respond_to do |r|
      if @group.save
        @membership = @group.memberships.create(:user_id => current_user.id, :admin => true)
        if @membership.save
          flash[:success] = "Successfully added group"
          r.html { redirect_to root_path }
        else
          @group.delete
          r.html { render :action => "new" }
        end
      else
        r.html { render :action => "new" }
      end
    end
  end
  def show
    @group = Group.find(params[:id])
    @users = @group.users
    @invitation = Invitation.new
    @admins = @group.memberships.where(:admin => true).map { |t| t.user }
    @uninvited = User.all.find_all do |u|
      not @group.invited?(u) and not @group.member?(u) and not @admins.include?(u)
    end
  end
  def invite
    @group = Group.find(params[:id])
    @invitation = Invitation.new(params[:invitation])
    @invitation.update_attributes(:group_id => @group.id)
    respond_to do |r|
      if @invitation.save
        flash[:success] = "Successfully invited user"
        r.html { redirect_to :action => "show" }
      else
        r.html { render :action => "show" }
      end
    end
  end
  def accept
    invitation = Invitation.find(params[:inv])
    @membership = current_user.memberships.new(:group_id => invitation.group_id, :admin => false)
    invitation.delete
    @membership.save if params[:accept]
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @groups = Group.all
    if user_signed_in?
      indexes = Membership.where(:user_id => current_user.id, :admin => true).map { |m| m.group_id }
      @owned_groups = Group.where(:id => indexes)
      #yeah, yeah
      indexes = Membership.where(:user_id => current_user.id, :admin => false).map { |m| m.group_id }
      @member_groups = Group.where(:id => indexes)
      @invitations = current_user.invitations
      @membership = Membership.new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
%p
  = f.label :Name
  = f.text_field :name
%p
  = f.label :Description
  %br
  = f.text_area :desc
  %br
  = f.submit "Create"

app/views/groups/new.html.haml
%h1
  Here you can create new group!
= form_for @group do |f|
  = render :partial => 'form', :locals => {:f => f}

app/views/groups/show.html.haml
%h1
  = @group.name
%p
  %h2
    Description:
  %br
  = @group.desc
  %h3
    Members:
  - for member in @group.users
    = member.email
    %br
  %h4
    Admins:
  - for admin in @admins
    = admin.email
    %br
  - if @admins.include?(current_user)
    %h5
      Invite:
    - form_for @invitation, :url => invite_group_path(@group) do |f|
      = f.select(:user_id, options_for_select(@uninvited.map { |u| [u.email, u.id] }))
      = f.submit "Invite", :disabled => (@uninvited.length == 0)
= link_to "Come back", root_path

app/views/home/index.html.haml
%div#left
  Groups available:
  %ul
    - for group in @groups
      %li= link_to group.name, group_path(group)
%div#right
  - if user_signed_in?
    - if not @invitations.empty?
      %div
        You've got some invites:
        %ul
        - for invite in current_user.invitations
          %li
            = link_to invite.group.name, group_path(invite.group)
            = link_to "Accept", group_accept_path(invite.group, :accept => true, :inv => invite), :method => :post
            = link_to "Reject", group_accept_path(invite.group, :accept => false, :inv => invite), :method => :post
    - if not @owned_groups.empty?
      %div
        You own:
        %ul
          - for owned in @owned_groups
            %li= link_to owned.name, group_path(owned)
    - if not @member_groups.empty?
      %div
        You are a member here:
        %ul
          - for member in @member_groups
            %li= link_to member.name, group_path(member)
    %p
      = link_to "Create new group", new_group_path
    %p
      Tired?
      = link_to "Sign out", destroy_user_session_path
  - else
    %p
      Wanna create?
      = link_to "Sign in!", new_user_session_path
    %p
      No account?
      = link_to "Sign up!", new_user_registration_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoRZad7</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>